# Generated by Django 4.0.5 on 2022-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plaintext', models.CharField(max_length=30)),
                ('key', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ciphers',
                'db_table': 'Cipher',
            },
        ),
        migrations.CreateModel(
            name='Decipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciphertext', models.CharField(max_length=30)),
                ('key', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Deciphers',
                'db_table': 'Decipher',
            },
        ),
    ]
