# Generated by Django 4.0.5 on 2022-08-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cipher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='decipher',
            options={},
        ),
        migrations.AlterModelTable(
            name='cipher',
            table=None,
        ),
        migrations.AlterModelTable(
            name='decipher',
            table=None,
        ),
    ]
