# Generated by Django 4.0.5 on 2022-08-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_alter_cipher_options_alter_decipher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipher',
            name='key',
        ),
        migrations.RemoveField(
            model_name='decipher',
            name='key',
        ),
    ]
